#!/bin/sh
cat "$@" | paste - - | \
	awk -F'\t' '
		{
			split($1, header_parts, ">| ");
			contig_name = header_parts[2];
			split($2, bases, "");
			gc_count=0;
			for (i=1; i <= length($2); i++) {
				if (bases[i] == "G" || bases[i] == "C")
					gc_count++;
			}
			printf("%s\t%.4f\n", contig_name, gc_count/length($2));
		}
	'
