#!/bin/sh
# I am using my own calculation here because the gc() function
# built into bioawk includes non-AGCT (e.g. 'N') chars in the
# denominator, and I don't want that.
bioawk -c fastx '{
	atgc_count=0;
	gc_count=0;
	SEQ=toupper($seq);
	split(SEQ, bases, "");
	for (i=1; i <= length(SEQ); i++) {
		if (bases[i] == "A" || bases[i] == "T" ||
			bases[i] == "G" || bases[i] == "C")
			atgc_count++;
		if (bases[i] == "G" || bases[i] == "C")
			gc_count++;
	}
	printf("%s\t%.4f\n", $name, gc_count/atgc_count);
}' "$@"
